apiVersion: v1
kind: Service
metadata:
  name: task4-service
  labels:
    type: web
spec:
  selector:
    task: task4
  type: NodePort
  ports:
    - nodePort: 31113
      port: 81
      targetPort: 80  
